WebUI/Models/BooksListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }      // Общее кол-во книг
        public int ItemsPerPage { get; set; }    // Кол-во книг на странице
        public int CurrentPage { get; set; }     // Номер текущей страницы
        public int TotalPages                    // Общее кол-во страниц
        {
            get { return (int)Math.Ceiling((decimal)TotalItems/ItemsPerPage); }
        }
    }
}

WebUI/Controllers/AdminController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        IBookRepository repository;
        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index()
        {
            return View(repository.Books);
        }
    }
}

WebUI/Controllers/BooksController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 4;
        public BooksController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books
            .Where(b => genre == null||b.Genre==genre)
            .OrderBy(book => book.BookId)
            .Skip((page - 1) * pageSize)
            .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null?
                    repository.Books.Count():
                    repository.Books.Where(book=> book.Genre==genre).Count()
                },
                CurrentGenre = genre
            };
            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IBookRepository repo,IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }
        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        //public Cart GetCart()
        //{
        //    Cart cart = (Cart)Session["Cart"];
        //    if(cart==null)
        //    {
        //        cart = new Cart();
        //        Session["Cart"] = cart;
        //    }
        //    return cart;
        //}
        public RedirectToRouteResult AddToCart(Cart cart, int bookId,string returnUrl)
        {
                Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);
                if(book!=null)
                {
                   cart.AddItem(book, 1);
                }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int bookId, string returnUrl)
        {
            Book book = repository.Books
            .FirstOrDefault(b => b.BookId == bookId);
            if (book != null)
            {
                cart.RemoveLine(book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
           if (cart.Lines.Count()==0)
            {
                ModelState.AddModelError("", "Извините, корзина пуста!");
            }
           if(ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
           else
            {
                return View(new ShippingDetails());
            }
        }
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        private IBookRepository repository;
        public NavController(IBookRepository repo)
        {
            repository = repo;
        }
        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;
            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);
            return PartialView("FlexMenu",genres);
        }
    }
}

WebUI/Views/Admin/Index.cshtml
@model IEnumerable<Domain.Entities.Book>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.BookId }) |
            @Html.ActionLink("Details", "Details", new { id=item.BookId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.BookId })
        </td>
    </tr>
}

</table>

WebUI/Views/Books/List.cshtml
 @using WebUI.Models
@model BooksListViewModel

@{
    ViewBag.Title = "Книги";
}

@foreach (var book in Model.Books)
{
    @Html.Partial("_BookSummary",book)
}
<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo,x=> Url.Action("List",new { page = x, genre= Model.CurrentGenre}))
</div>


WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "BookStore : форма заказа";
}

<h2>Оформить заказ</h2>
<p>Пожалуйста, введите Ваши контактные данные</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя :</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if(property.PropertyName !="Name" && property.PropertyName !="GiftWrap")
        {
            <div class="form-group">
                <label>
                    @(property.DisplayName??property.PropertyName)
                </label>
                @Html.TextBox(property.PropertyName,null,new { @class = "form-control"})
            </div>
        }
    }
    <div class="form-group">
        <label>Первый адрес:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Третий адрес:</label>
        @Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Город:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Страна:</label>
        @Html.TextBoxFor(x => x.Counttry, new { @class = "form-control" })
    </div>
    <h3>Опции</h3>
    <div class="form-group">
        <label>
            @Html.EditorFor(x=>x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ"/>
    </div>
}


WebUI/Views/Cart/Completed.cshtml

@{
    ViewBag.Title = "Заказ принят";
}

<h2>Спасибо</h2>
<p>
    Спасибо за выбор нашего Магазина. Ожидайте ваш заказ в ближайшее время.
</p>


WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "BookStore : Корзина";
}
<h2>@ViewBag.Title</h2>
<table class="table" style="vertical-align:middle">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th> 
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Book.Name - @line.Book.Author</td>
            <td class="text-right">@line.Book.Price.ToString("# BYN")</td>
            <td class="text-right">@((line.Quantity * line.Book.Price).ToString("# BYN"))</td>
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("BookId",line.Book.BookId)
                    @Html.HiddenFor(x=>x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="Удалить"/>
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого: </td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# BYN")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Вернуться в магазин</a>
    @Html.ActionLink("Оформить заказ","Checkout",null,new { @class="btn btn-primary"})
</div>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Корзина", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new{returnUrl= Request.Url.PathAndQuery}) class="btn btn-default navbar-btn">
       <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>
<div class="navbar-text navbar-right">
    <b>У вас :</b>
    @Model.Lines.Sum(x=>x.Quantity) книг,
    @Model.ComputeTotalValue().ToString("# BYN")
</div>

WebUI/Views/Nav/FlexMenu.Mobile.cshtml
@model IEnumerable<string>

<div data-role="navbar">
    <ul>
        @foreach (var link in Model)
         {
            <li>
                @Html.RouteLink(link, new
              {
               controller = "Books",
               action = "Link",
               genre = link,
               page = 1
              }, new
              {
               data_transition="fade",
               @class = (link==ViewBag.SelectedGenre?"ui-btn-active":null)
              })
            </li>
         }
    </ul>
</div>

WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{ 
    bool horizontal = (bool)(ViewContext.RouteData.Values["horizontal"] ?? false);
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}
<div class="@wrapperClasses">
    @Html.ActionLink("Домой", "List", "Books", null,
    new
    {
        @class = horizontal?"btn btn-default btn-sm":"btn btn-block btn-default btn-lg"
    })
    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
   {
       controller = "Books",
       action = "Link",
       genre = link,
       page = 1
   }, new
   {
       @class = (horizontal ? "btn btn-default btn-sm" : "btn btn-block btn-default btn-lg")
            + (link == ViewBag.SelectedGenre ? "btn-primary" : "")
   })
 }

</div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Главная", "List","Books",null,new { @class = "btn btn-block btn-default btn-lg"})

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
{
    controller = "Books",
    action = "List",
    genre = link,
    page = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
    + (link == ViewBag.SelectedGenre? "btn btn-lg btn-primary" : "")
})

}

WebUI/Views/Shared/_AdminLayout.cshtml
@{ 
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet"/>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_BookSummary.Mobile.cshtml
@model Domain.Entities.Book

<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
    <h2>@Model.Name</h2>
    <h3>@Model.Author</h3>
    <div>
        <div>
            @Model.Description
        </div>
    <div>
        <strong>@Model.Price.ToString("# BYN")</strong>
    </div>
    <div>
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            @Html.HiddenFor(x => x.BookId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="В корзину" />
        }
    </div>
</div>
</div>

WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book
<div class="well">
    <div class="row">
        <div class="col-xs-9">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Author</strong>
            </h4>
        </div>
        <div class="col-xs-3">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                @Model.Price.ToString("# BYN")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div>
                    @Html.HiddenFor(x=>x.BookId)
                    @Html.Hidden("returnUrl",Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success"  value="В корзину"/>
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.Description></span>
</div>

WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile.1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
        <div data-role="page" id="page1">
            <div data-theme="a" data-role="header" data-position="fixed">
                <h3>BookStore</h3>
                @Html.Action("Menu","Nav")
            </div>
            <div data-role="content">
                <ul data-role="listview" data-dividertheme="b" data-inset="false">
                    <li>@RenderBody()</li>
                </ul>
        </div data-role="content">
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
      
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs" href="#">BookStore</span>
            <div class="visible-xs">Book</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="visible-xs">
        @Html.Action("Menu","Nav", new { horizontalNav = true })
    </div>
    <div class="row panel">
        <div id="genres" class="col-sm-3 hidden-xs">
        @Html.Action("Menu", "Nav")
        </div>
    <div class="col-xs-12 col-sm-8">
        @RenderBody()
    </div>
        </div>
</body>
</html>